- hosts: vmhosts
  tasks:
    - name: Install yum-utils package
      dnf: name=yum-utils state=present update_cache=true
      become: true
    - name: Install epel package
      dnf: name=epel-release state=present update_cache=true
      become: true
    - name: Install epel next package
      dnf: name=epel-next-release state=present update_cache=true
      become: true
    - name: Add multiple repositories into the same file (1/2)
      become: true
      yum_repository:
        name: Hashicorp.Stable
        description: Hashicorp Repo for Centos  
        baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
        gpgkey: https://rpm.releases.hashicorp.com/gpg
        gpgcheck: true

        
