- hosts: vmhosts
  tasks:
  - name: Install virt package
    dnf: name=virt-install state=present update_cache=true
    become: true
  - name: Install QEMU package
    dnf: name=qemu-kvm state=present update_cache=true
    become: true
  - name: Install libvirt package
    dnf: name=libvirt state=present update_cache=true
    become: true
  - name: Install packer
    become: true
    dnf: name=packer state=present update_cache=true
  - name: Install virt-manager
    become: true
    dnf: name=virt-manager state=present update_cache=true
  - name: Install libguestfs-tools
    become: true
    dnf: name=libguestfs-tools state=present update_cache=true